services:
  app:
    container_name: todo-api
    build:
      dockerfile: ./Dockerfile.app
      context: .
    volumes:
      - type: bind
        source: ./
        target: /src
    ports:
      - "8080:8080"
    tty: true
    environment:
      PORT: ":8080"
      TODO_DB_HOST: db
      TODO_DB_PORT: 3306
      TODO_DB_USER: user
      TODO_DB_PASSWORD: pswd
      TODO_DB_NAME: todo-db
      TODO_KVS_HOST: kvs
      TODO_KVS_PORT: 6379
    depends_on:
      - db
      - kvs
  db:
    container_name: todo-db
    image: mysql:8.0.40-debian
    platform: linux/amd64
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
      - type: bind
        source: ./app/infrastructure/db/mysql
        target: /etc/mysql/conf.d:cached
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo-db
      MYSQL_USER: user
      MYSQL_PASSWORD: pswd
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    tty: true
  kvs:
    container_name: todo-kvs
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: kvs-store
        target: /data
    tty: true
volumes:
  db-store:
  kvs-store: